services:
  postgres:
    image: postgres:16
    container_name: gamificacao-postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_DB: gamificacao_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # healthcheck para garantir que a API so suba depois que o banco aceitar conexao
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gamificacao_db"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s
    networks:
      - app_net

  pgadmin:
    image: dpage/pgadmin4:9
    container_name: gamificacao-pgadmin
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - app_net

  app:
    build: .
    container_name: gamificacao-app
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/gamificacao_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - app_net

volumes:
  postgres_data:
  pgadmin_data:

networks:
  app_net:
    driver: bridge
