spring.application.name=Grupo_7_PraticaATDD

spring.profiles.active=${SPRING_PROFILES_ACTIVE:h2}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

springdoc.swagger-ui.path=/swagger-ui.html
